export const ORIENTATION = ['all', 'landscape', 'portrait', 'square'];
export const SIZES = ['any', 'large', 'medium', 'small'];
export const COLORS = ['any', 'red', 'blue', 'green', 'black'];
export const queries = [
  'nature',
  'pets',
  'flowers',
  'sport',
  'art',
  'technologies',
  'galaxy',
  'business',
  'basketball',
  'beach',
  'football',
  'tennis',
  'city',
  'hockey',
  'soccer',
  'programming',
  'python',
  'java',
  'cars',
  'food',
  'space',
  'textures',
  'asteroids',
  'earth',
  'mars',
  'jupiter',
  'moon',
  'mountains',
  'rocks',
  'coffee',
  'tea',
  'restaurants',
  'morning',
  'evening',
  'night',
  'winter',
];
